### ISSUE TITLE
Can Vines implement group chat?

### ISSUE THREAD

**Issue by jstdoit** [negativecode/vines#29]
Can Vines implement group chat?

**Comment by scrothers** [comment]
What functionality are you looking for using a MUC? (Multi-User Chat in Jabber)

Perhaps someone can better instruct you on how to accomplish what your ultimate goal is?

**Comment by jstdoit** [comment]
I just wanna a xmpp server completely written in Ruby, here I got Vines. But some features were not implemented, especially MUC, so, I want to know if there is any plan about implementing more features.

**Comment by jstdoit** [comment]
as above

**Comment by scrothers** [comment]
Ah, fair question then. To be honest, I've only spent the past couple weeks familiarizing myself with the code. However, adding MUC support would be fairly difficult at this point. Firstly, it would require full implementation of the XEP for a MUC.

Secondly, the part I see as hard, is that you would have to create another service entirely to handle the MUCs. It's not quite as simple as "oh add these stanzas", because of the way Jabber works. Essentially the MUC would function as it's own psuedo service, while implementing is more than half done because, hey, we have a working Jabber server sitting right here. The problem is extending what's here even further.

Not an insignificant change really, ideally, it seems you want to use Vines as a simple chat server between users. If we could come up with a case as to why a MUC is useful to server management, we could probably gain some traction and I could start writing it a bit and hopefully others would join in.

My $0.02

**Comment by jstdoit** [comment]
of course, if I just want to use Vines as a simple chat server, I'd better choose to use openfire or something else. I just want a most complete xmpp server written in Ruby. Anyway, if there's anyone who wanted to start completing these doings, I'm happy to contribute.

BTW, what's your "My $0.02"?

**Comment by brodock** [comment]
Group chat could be used to help control cluster of servers. I can imagine a lot of cool useful use cases, where someone could invoke commands that will be "broadcasted" to the whole group (cluster) and things like that.

And I also would love to have a fully functional ruby server to be used for "chat" and support.
I see that your current focus is on server communication, but I do believe that you can also potentially pivotate into "help desk" and "click here to talk with the support" (BOSH,etc).
This market is huge and can give you enough money stream to keep it going on.

**Comment by brodock** [comment]
This is related to #7

**Comment by jimhj** [comment]
+1

**Comment by sammcj** [comment]
+1
